#ifndef VK_MANDELBROT_UIEVENTS_HPP
#define VK_MANDELBROT_UIEVENTS_HPP

enum UiEventTypes
{
    UET_EXIT,
    UET_MOUSE_EXCLUSIVE,
    UET_INVERT_MOUSE_AXIS,
    UET_FULLSCREEN,
    UET_PAUSE_START_PARTICLES,
    UET_RESET_PARTICLES,
    UET_GENERATE_SPHERE,
    UET_GENERATE_CUBE,
    UET_SET_PARTICLES_NUMBER,
    UET_SET_PARTICLES_COLOR,
    UET_GENERATE_DISK,
    UET_SET_PARTICLE_MAX_SPEED,
    UET_TOTAL_NB,
};

struct UiEvent
{
    bool events[UET_TOTAL_NB] = { false };
};

#endif // VK_MANDELBROT_UIEVENTS_HPP
